<?php


namespace Controller;


class PageController extends DisplayController
{
    protected $page;
    protected $alias;
    public function execute($param = [])
    {
        $page = $param['page'];
        $this->page = $page ? $page : 1;
        $this->alias = $param['alias'];

        $this->display();
    }

    protected function display()
    {
        $items = $this->model->getItems($this->page,$this->alias);
        foreach ($items['items'] as $item){
            $row[] = $item;
        }
        $items['items'] = $row;
        $this->main = $this->app->view()->fetch('page.tpl.php', [
            'uri' => $this->uri,
            'app' => $this->app,
            'items' => $items['items'],
            'navigation' => $items['navigation'],
        ]);

        parent::display(); // TODO: Change the autogenerated stub
    }
}