<?php


namespace AdminController;

use Controller\DisplayController;

class AdminController extends DisplayController
{
   protected $template = 'dashboard/layout/dashboard.tpl.php';

   public function index(){
       $this->index = $this->app->view()->fetch('dashboard/main.tpl.php');
       $this->display();
   }

    protected function display()
    {
        $this->main = $this->index;
        parent::display(); // TODO: Change the autogenerated stub
    }
}