<?php


namespace AdminController;


class ParserController extends AdminController
{
    public function index(){

        $this->index = $this->app->view()->fetch('dashboard/parser.tpl.php');
        $this->display();

    }

    protected function display(){
        $this->main = $this->index;
        parent::display(); // TODO: Change the autogenerated stub
    }
}