<?php


namespace AdminController;


class PostController extends AdminController
{
    public function index(){

        $this->index = $this->app->view()->fetch('dashboard/posts.tpl.php');
        $this->display();

    }

    public function add(){
        $this->index = $this->app->view()->fetch('dashboard/addPost.tpl.php');
        $this->display();
    }

    protected function display(){
        $this->main = $this->index;
        parent::display(); // TODO: Change the autogenerated stub
    }


}