<?php


namespace AdminController;


use Lib\Helper;
use Lib\Upload;
use Model\AttrCat;
use Model\Attributes;
use Model\AttrProduct;
use Model\CatProduct;
use Model\Image;
use Model\Product;

class ShopController extends AdminController
{
    public function add(){
        $attrDB = new AttrCat();
        $attrPrDB = new AttrProduct();
        $productBD = new Product();
        $imgDB = new Image();
        $attrs = $attrDB->getAttrCat($_POST['cat']);
        $productBD->add([
            'name_product' => $_POST['title'],
            'price_product' => $_POST['price'],
            'img_product' => Upload::can_upload($_FILES['img1'])?Upload::make_upload($_FILES['img1']):'',
            'text_product' => $_POST['text'],
            'id_cat_pr' => $_POST['cat']
        ]);

        $id_product = $productBD->driver->lastInsertId();
        for($i = 2; $i < count($_FILES) + 1; $i++){
            if (Upload::can_upload($_FILES['img'.$i])){
                $imgDB->add([
                    'id_product' => $id_product,
                    'url_img' =>   Upload::make_upload($_FILES['img'.$i])
                ]);
            }
        }
        foreach ($attrs as $attr){
            $attrPrDB->add([
                'id_attr' => $attr['id_attr'],
                'id_product' => $id_product,
                'val_attr' => $_POST[$attr['alias_attr']]
            ]);
        }
      $this->app->redirectTo('viewAdd');
    }

    public function viewAdd(){
        $pr = new Product();
        $catDB = new CatProduct();
        $attrDB = new AttrCat();
        $cats = $catDB->row('id_cat_pr,name_cat');
        $attr = $attrDB->getAttrCat($cats[0]['id_cat_pr']);
        $this->index = $this->app->view()->fetch('dashboard/addProduct.tpl.php',[
            'cats' => $cats,
            'uri' => $this->getUri(),
            'helper' => Helper::getInstance(),
            'attr' => $attr
        ]);
        $this->display();
    }

    public function viewAttr(){
        $attrDB = new AttrCat();
        $attr = $attrDB->getAttrCat($_POST['id_cat']);
        $result = '';
        foreach ($attr as $value){
            $result .= $this->app->view()->fetch('dashboard/attr.tpl.php', [
                'value' => $value
            ]);
        }
       echo json_encode(['html' => $result, 'status' => 200]);
        exit();
    }


    protected function display(){
        $this->main = $this->index;
        parent::display(); // TODO: Change the autogenerated stub
    }
}