<?php


namespace AdminController;


use Lib\Cache;
use Lib\Helper;
use Model\Post;
use Model\Slider;

class SliderController extends AdminController
{
    protected $sliderDB;
    public function __construct()
    {
        $this->sliderDB = new Slider();
        parent::__construct();
    }

    public function index(){
        $sliders = $this->sliderDB->getSliderForDashboard();
        $this->index = $this->app->view()->fetch('dashboard/slider.tpl.php', [
            'sliders' => $sliders,
            'helper' => Helper::getInstance(),
            'uri' => $this->getUri(),
        ]);
        $this->display();
    }
    public function edit(){
        $postBD = new Post();
        $postID = $postBD->getPostWithTitleAndTv($_POST['title'], $_POST['tv']);
        $cache = new Cache();
        $cache->delete('slider');
        if ($postID){
            $this->sliderDB->updateSlide($postID['id'], $_POST['img'], $_POST['id_slider']);
            echo  json_encode(['status' => 200]);
        }else{
            echo  json_encode(['status' => 500]);
        }

    }

    public function add(){
        $postBD = new Post();
        $postID = $postBD->getPostWithTitleAndTv($_POST['title'], $_POST['tv']);
        $cache = new Cache();
        $cache->delete('slider');
        if ($postID){
            $this->sliderDB->addSlide($postID['id'], $_POST['img']);
            $slide = $this->sliderDB->getSliderForDashboard('ORDER BY lite_slider.id DESC LIMIT 1');
            $result = $this->app->view()->fetch('dashboard/list_slide.tpl.php',[
                'slider' => $slide[0],
                'helper' => Helper::getInstance(),
            ]);
            echo  json_encode(['status' => 200, 'html' => $result]);
        }else{
            echo  json_encode(['status' => 500]);
        }
    }

    public function delete(){
        if ($this->sliderDB->deleteSlide($_POST['id_slider'])){
            echo  json_encode(['status' => 200]);
        }else{
            echo  json_encode(['status' => 500]);
        }
        $cache = new Cache();
        $cache->delete('slider');
        exit();
    }
    protected function display()
    {
        $this->main = $this->index;
        parent::display(); // TODO: Change the autogenerated stub
    }

}
