<?php


namespace Controller;
defined('_Sdef') or exit();


class AdminController extends DisplayController
{
    protected function display($tmpl = false)
    {
    parent::display($tmpl); // TODO: Change the autogenerated stub
    }

    public function execute($param = [])
    {
        return $this->display();
    }
}