<?php


namespace Controller;


class CategoryController extends DisplayController
{
    public function execute($param = [])
    {
        return parent::execute($param); // TODO: Change the autogenerated stub
    }

    public function display()
    {

        parent::display(); // TODO: Change the autogenerated stub
    }
}