<?php


namespace Controller;
defined('_Sdef') or exit();

class IndexController extends DisplayController
{
    protected $page;
    public function execute($param = [])
    {
        $page = $param['page'];
        $this->page = $page ? $page : 1;
        return $this->display();
    }

    protected function display()
    {


        $this->main = $this->app->view()->fetch('indexbar.tpl.php',[
            'app' => $this->app,
            'uri' => $this->uri
        ]);
        parent::display(); // TODO: Change the autogenerated stub
    }

}