<?php


namespace Controller;


use Lib\Helper;

class PageController extends DisplayController
{
    protected $page;
    protected $alias;
    protected $index;
    public function execute($param = [])
    {


        $page = $param['page'];
        $this->page = $page ? $page : 1;
        $this->alias = $param['alias'];

        $this->display();
    }


    public function post($param = []){
      $page =  $param['page'];

      preg_match('#\d+#', $page, $matches);

        $post = $this->model->getPost($matches[0]);
        $cat = $this->model->getCatPost($post['id_post']);
        $countCat = count($cat);
        $player = 
        $this->index = $this->app->view()->fetch('post.tpl.php',[
            'uri' => $this->uri,
            'cat' => Helper::renderCat($cat,$countCat),
            'post' => $post
        ]);

        $this->display();
    }

    public function allPost($param = []){
        $page = $param['page'];
        $this->page = $page ? $page : 1;
        $this->alias = $param['alias'];
        $path = $this->app->request->getPath();
        preg_match('#/\d+#', $path, $mathces);
        $path = str_replace($mathces[0], '', $path);
        $path .= '/';
        $items = $this->model->getItems($this->page,$path,$this->alias);
        foreach ($items['items'] as $item){
            $row[] = $item;
        }
        $items['items'] = $row;
        $this->index = $this->app->view()->fetch('page.tpl.php', [
            'uri' => $this->uri,
            'app' => $this->app,
            'items' => $items['items'],
            'navigation' => $items['navigation'],
            'helper' => Helper::getInstance(),
        ]);
    $this->display();
    }

    protected function display()
    {
        $this->main = $this->index;

        parent::display(); // TODO: Change the autogenerated stub
    }
}