<?php


namespace Controller;


use Lib\Helper;

class ProfileController extends DisplayController
{
    protected $index;
    public function viewProfile(){
        $this->index = $this->app->view()->fetch('profile.tpl.php',[
            'uri' => $this->uri,

        ]);
        $this->display();
    }

    public function display()
    {
        $this->main = $this->index;
        parent::display(); // TODO: Change the autogenerated stub
    }

}