<?php


namespace Controller;
defined('_Sdef') or exit();

use Lib\Helper;

class ProfileController extends DisplayController
{
    protected $index;
    public function viewProfile($param = []){
        $user = $this->model->getUser($param['login']);
        if (empty($user)){
            $this->app->notFound();
        }
        $this->index = $this->app->view()->fetch('profile.tpl.php',[
            'uri' => $this->uri,
            'user' => $user,
            'helper' => Helper::getInstance(),
        ]);
        $this->display();
    }

    public function display()
    {
        $this->main = $this->index;
        parent::display(); // TODO: Change the autogenerated stub
    }

}