<?php


namespace Controller;


class RegistController extends DisplayController
{
    protected $index;

    public function formView(){
        $this->index = $this->app->view()->fetch('regist.tpl.php');
        $this->display();
    }

    public function registration(){

    }
    protected function display()
    {
        $this->main = $this->index;
        parent::display(); // TODO: Change the autogenerated stub
    }

}