<?php


namespace Controller;


use Lib\Helper;
use Model\Attributes;
use Model\Product;

class ShopController extends DisplayController
{
    public function index($page){
        $this->title = 'Купить Манга - японские комиксы на русском языке онлайн';
        $this->description = 'В интернет-магазине «Animehub» вы можете купить японские комиксы манга в Таджикистане, Душанбе и Худжанд. У нас самые низкие цены и быстрая доставка.';
        $this->keywords = 'Купить мангу, Таджикистан, Душанбе, Худжанде, на русском, купить мангу в Таджикистане';
        $comments = [];
        $productDB = new Product();
        $page = $page ? $page : 1;
        $products = $productDB->getProductList($page,'/shop');
        if (empty($products['items'])){
            $this->app->notFound();
        }
        $this->index = $this->app->view()->fetch('shop.tpl.php',[
           'products' => $products['items'],
            'helper' => Helper::getInstance(),
            'uri' => $this->getUri(),
            'search' => $this->getSearch('Манга'),
            'comments' => $comments,
            'navigation' => $products['navigation']
        ]);
        $this->display();
    }

    public function store($product){
        preg_match('#\d+#', $product, $matches);
        $productDB = new Product();
        $attrDB = new Attributes();
        $attrs = $attrDB->getAttributes($matches[0]);
        $pr = $productDB->getProductInfo($matches[0]);
        $this->title = 'Купить мангу «'.$pr['name_product'].'» по выгодной цене в магазине комиксов «Comic Street»';
        $this->description = 'В аниме-магазине «Animehub»'.$pr['name_product'].'» У нас низкие цены на мангу и быстрая доставка.';
        $this->keywords = 'Купить мангу '.$pr['name_product'].', Таджикистан, Душанбе, Худжанде, на русском, купить мангу в Таджикистане';
        $similar = $productDB->getProductSimilar($pr['id_cat_pr'], 5);
        $this->index = $this->app->view()->fetch('store.tpl.php', [
            'product' => $pr,
            'uri' => $this->getUri(),
            'helper' => Helper::getInstance(),
            'attrs' => $attrs,
            'similar' => $similar
        ]);
        $this->display();
    }
    protected function display()
    {
        $this->main = $this->index;
        parent::display(); // TODO: Change the autogenerated stub
    }
}