<?php


namespace Controller;


use Lib\Helper;
use Model\Attributes;
use Model\Product;

class ShopController extends DisplayController
{
    public function index(){
        $productDB = new Product();
        $products = $productDB->getProduct();
        $this->index = $this->app->view()->fetch('shop.tpl.php',[
           'products' => $products,
            'helper' => Helper::getInstance(),
            'uri' => $this->getUri(),
            'search' => $this->getSearch(),
        ]);
        $this->display();
    }

    public function store($product){
        preg_match('#\d+#', $product, $matches);
        $productDB = new Product();
        $attrDB = new Attributes();
        $attrs = $attrDB->getAttributes($matches[0]);
        $pr = $productDB->getProductInfo($matches[0]);
        $similar = $productDB->getProductSimilar($pr['id_cat_pr'], 5);
        $this->index = $this->app->view()->fetch('store.tpl.php', [
            'product' => $pr,
            'uri' => $this->getUri(),
            'helper' => Helper::getInstance(),
            'attrs' => $attrs,
            'similar' => $similar
        ]);
        $this->display();
    }
    protected function display()
    {
        $this->main = $this->index;
        parent::display(); // TODO: Change the autogenerated stub
    }
}