<?php


namespace Controller;
defined('_Sdef') or exit();

class WidgetController extends DisplayController
{
    protected $index;


    public function viewQuestionnaire(){

        if (!isset($_SESSION['auth'])){
            $this->app->notFound();
        }elseif($_SESSION['status'] != 'Админ'){
            $this->app->notFound();
        }
        $this->index = $this->app->view()->fetch('Admin/oprosnik.php', [
            'uri' => $this->uri,
            'app' => $this->app,

        ]);
        $this->display();
    }

    public function addQuestionnaire(){
        if (!empty($_POST['q'])){
           $id_quest = $this->model->addQuestion($_POST['q']);
           for($i = 1; $i <= 4; $i++){
               if (!empty($_POST['a'.$i])){
                   $this->model->addAnswers($id_quest,$_POST['a'.$i]);
               }else{
                   break;
               }
           }

        }
    }
    protected function display()
    {
        $this->main = $this->index;
        parent::display(); // TODO: Change the autogenerated stub
    }
}